# Generated by Django 5.2.17 on 2026-09-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavor',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='flavors',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.flavor'),
        ),
    ]
