# Generated by Django 5.2.17 on 2026-09-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_flavor_product_product_flavors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_precent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
