# Generated by Django 5.2.17 on 2026-09-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='lang_prefix',
            field=models.CharField(default='en', max_length=100),
        ),
    ]
