# Generated by Django 5.2.17 on 2026-09-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_language_lang_prefix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total_price_base',
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price_customer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
